language: node_js
node_js:
  - "6.5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database ce100_test; create table organisations; create table people; insert into organisations (id) values (1); insert into people (id) values (1)' -U postgres
before_install:
  - pip install --user codecov
  - $CXX --version
after_success:
  - codecov --file coverage/lcov.info --disable search
